BVTCApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('orders', views.orders, name='orders'),
    path('orders/add_order', views.add_order, name='add_order'),
    path('orders/add_order/add_item', views.add_item, name='add_item'),
    path('quotations', views.quotations, name='quotations'),
]

BVTC_Project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('BVTCApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BVTCApp/models.py
from django.db import models
from django.utils import timezone

class UserAccount(models.Model): ## double check CHOICES match ui
    USER_TITLES = [
         ('Admin', 'Admin'),
         ('Account Manager', 'Account Manager'),
         ('Production', 'Production'),
         ('Sales Officer', 'Sales Officer'),
         ('Marketing Officer', 'Marketing Officer'),
         ('Graphic Designer', 'Graphic Designer'),
    ]

    USER_ROLES = [
         ('Admin', 'Admin'),
         ('Account Manager', 'Account Manager'),
         ('Officer', 'Officer'),
         ('Other', 'Other'),
    ]
    
    user_id = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=50)
    password = models.CharField(max_length=255)
    user_title = models.CharField(max_length=50, choices=USER_TITLES)
    user_role = models.CharField(max_length=100, choices=USER_ROLES, default='Other')

class Company(models.Model):
    company_id = models.AutoField(primary_key=True)
    company_name = models.CharField(max_length=150)
    company_logo = models.CharField(max_length=255)
    company_address = models.CharField(max_length=255)
    tin_number = models.CharField(max_length=15, unique=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.company_id} - {self.company_name}'
    
    class Meta:
        verbose_name_plural: str = 'Companies'

class CustomerAccount(models.Model):
    customer_id = models.AutoField(primary_key=True)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=100)
    customer_email = models.CharField(max_length=100)
    customer_phone_number = models.CharField(max_length=20)
    messenger = models.CharField(max_length=100, blank=True, null=True)
    viber = models.CharField(max_length=15, blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.customer_id} - {self.customer_name}, {self.company_id}'

    class Meta:
        verbose_name_plural: str = 'Customer Accounts'

class ShippingDetails(models.Model):
    shipping_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(CustomerAccount, on_delete=models.CASCADE)
    contact_person = models.CharField(max_length=150)
    contact_person_email = models.EmailField(max_length=100)
    contact_person_number = models.CharField(max_length=20)
    address_province = models.CharField(max_length=60)
    address_city = models.CharField(max_length=60)
    address_barangay = models.CharField(max_length=60)
    address_line_1 = models.CharField(max_length=100)
    address_line_2 = models.CharField(max_length=100, blank=True, null=True)
    address_postal_code = models.IntegerField()
    objects = models.Manager()

    def __str__(self):
        return f'{self.shipping_id} - {self.customer_id}, {self.contact_person}'

    class Meta:
        verbose_name_plural: str = 'Shipping Details'

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_code = models.CharField(max_length=20, unique=True, blank=True)
    product_name = models.CharField(max_length=150)
    category = models.CharField(max_length=100)
    description = models.TextField()
    starting_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    MOQ = models.PositiveIntegerField()
    objects = models.Manager()

    def __str__(self):
         return f'{self.product_code} - {self.product_name}'

class ProductImage(models.Model): #Composite Key
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_image = models.ImageField(upload_to='images/')
    objects = models.Manager()

    def __str__(self):
         return f'{self.product_id} - {self.product_image}'

    class Meta:
        verbose_name_plural: str = 'Product Images'

class ProductColor(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_color = models.CharField(max_length=100)
    objects = models.Manager()
    
    def __str__(self):
        return f'{self.product_id} - {self.product_color}'

    class Meta:
        verbose_name_plural: str = 'Product Colors'

class Order(models.Model): ### double check CHOICES match ui
    PAYMENT_MODES = [
         ('Metrobank Fund Transfer', 'Metrobank Fund Transfer'),
         ('BPI Bank Transfer', 'BPI Bank Transfer'),
         ('GCash Payment', 'GCash Payment'),
    ]

    PAYMENT_TERMS = [
         ('Partial', 'Partial'),
         ('Full', 'Full'),
    ]

    ORDER_STATUS = [
         ('Pending', 'Pending'),
         ('Approved for Production', 'Approved for Production'),
         ('In Production', 'In Production'),
         ('Completed', 'Completed'),
         ('Dispatched', 'Dispatched'),
         ('Delivered', 'Delivered'),
         ('Cancelled', 'Cancelled'),
    ]

    STOCK_AVAILABILITY = [
         ('Available', 'Available'), 
         ('Limited', 'Limited'), 
         ('Out of Stock', 'Out of Stock'),
    ]

    order_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(CustomerAccount, on_delete=models.CASCADE)
    user_id = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    shipping_id = models.ForeignKey(ShippingDetails, on_delete=models.CASCADE)
    
    mode_of_payment = models.CharField(max_length=50, choices=PAYMENT_MODES)
    payment_terms = models.CharField(max_length=20, choices=PAYMENT_TERMS)

    budget = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    initial_total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    start_of_production = models.DateField(default=timezone.now)
    delivery_date = models.DateField(blank=True, null=True)
    lead_time = models.PositiveIntegerField(default=1)

    transaction_platform = models.CharField(max_length=50)
    link_to_logo = models.CharField(max_length=500)

    packing_instructions = models.TextField(blank=True, null=True)
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS, default='Pending')

    freight_term = models.BooleanField(default=False)
    delivery_fee = models.BooleanField(default=False)

    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    issue_date = models.DateField(default=timezone.now)

    note = models.TextField(blank=True, null=True)

    stock_availability = models.CharField(max_length=20, choices=STOCK_AVAILABILITY, default='Available')
    customization_feasibility = models.CharField(max_length=100)
    lead_time_feasibility = models.PositiveIntegerField(default=0)

    actual_total_price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    def __str__(self):
        return f'{self.order_id} - {self.customer_id}'

class OrderItem(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.CharField(max_length=7, blank=True, null=True)
    customization = models.TextField(blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    objects = models.Manager()

    def __str__(self):
        return f'{self.order_id}-{self.product_id}'

    class Meta:
        verbose_name_plural: str = 'Order Items'

class BillingStatement(models.Model):
	billing_statement_id = models.AutoField(primary_key=True)
	order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
	billing_date = models.DateField(default=timezone.now)
	due_date = models.DateField(default=timezone.now)

class Image(models.Model): ## double check CHOICES match ui, Composite Key
    IMAGE_TYPES = [
         ('Customer Provided', 'Customer Provided'),
         ('In-House', 'In-House'),
         ('Sample', 'Sample'),
    ]

    IMAGE_STATUS = [
         ('Pending', 'Pending'),
         ('Approved', 'Approved'),
         ('Rejected', 'Rejected'),
    ]

    image_id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    image_path = models.CharField(max_length=255)
    feedback = models.TextField(blank=True, null=True)
    image_type = models.CharField(max_length=20, choices=IMAGE_TYPES)
    image_status = models.CharField(max_length=15, choices=IMAGE_STATUS, default='Pending')

BVTCApp/views.py
from django.shortcuts import render
from .models import Product, ProductImage, ProductColor, Order, OrderItem, Company, CustomerAccount, ShippingDetails

def catalog(request):
    products = Product.objects.all()
    return render(request, 'bvtc_app/catalog.html', {'products': products})

def orders(request):
    return render(request, 'bvtc_app/orders.html')

def add_order(request):
    return render(request, 'bvtc_app/add_order.html')

def add_item(request):
    return render(request, 'bvtc_app/add_item.html')

def quotations(request):
    return render(request, 'bvtc_app/quotations.html')

BVTCApp/templates/bvtc_app/add_item.html
{% extends 'bvtc_app/base.html' %}
{% load static %}

{% block title %}Add Item{% endblock %}

{% block nav %}
<h1 class="bold">Orders</h1>
<i class="material-symbols-outlined" style="font-size: 21px;">chevron_forward</i>
<h1 class="bold">Add New Order</h1>
<i class="material-symbols-outlined" style="font-size: 21px;">chevron_forward</i>
<h1 class="bold">Add Item</h1>
{% endblock %}

{% block orders_button %}
<button type="submit" style="background: #E9E6E3;">
    <i class="material-symbols-rounded" style="font-size: 24px;">assignment</i>
    <p class="button-text small-b">Orders</p>
</button>
{% endblock %}

{% block main %}
<div class="action-bar">
    <div class="horizontal-section">
        <h1>Add Item to Order</h1>
        <div class="horizontal-section" style="flex: 0;">
            <div class="vertical-section" style="flex: 0; gap: 3px;">
                <p class="small-r" style="white-space: nowrap;">Initial Items (0 Items): <b>₱ 0.00</b></p>
                <p class="smaller-r" style="color: #898989;" style="white-space: nowrap;">Discounted Total <i>(less 0%)</i>: <b>₱ 0.00</b></p>
            </div>
            <div class="horizontal-input-field">
                <a href="{% url 'add_order' %}" class="button-secondary small-m">Cancel</a>
                <button class="button-primary small-m">Done</button>
            </div>
        </div>
    </div>
</div>

<div class="action-bar">
    <div class="horizontal-section">
        <form action="" class="filter" style="flex-wrap: wrap;">
            <p class="small-r filter-name" style="padding: 6px 15px 6px 0px;">Filter:</p>
            <input class="filter-input" type="radio" name="filter" value="all" id="all" checked>
            <label class="filter-label small-b" for="all">All</label>

            <input class="filter-input" type="radio" name="filter" value="company-profile" id="company-profile">
            <label class="filter-label small-b" for="company-profile">Company Profile</label>

            <input class="filter-input" type="radio" name="filter" value="individual-items" id="individual-items">
            <label class="filter-label small-b" for="individual-items">Individual Items</label>

            <input class="filter-input" type="radio" name="filter" value="gift-set" id="gift-set">
            <label class="filter-label small-b" for="gift-set">Gift Set</label>

            <input class="filter-input" type="radio" name="filter" value="bag" id="bag">
            <label class="filter-label small-b" for="bag">Bag</label>
        </form>

        <div class="actions">
            <form action="" class="search-area">
                <input type="search" class="search-bar" placeholder="Search">
            </form>
        </div>
    </div>
</div>

<div class="catalog">
    <div class="product-card" data-modal="add-item-modal">
        <div class="thumbnail">
            <img src="https://drive.google.com/thumbnail?id=0B6wwyazyzml-OGQ3VUo0Z2thdmc&sz=w1000" alt="" class="thumbnail">
        </div>
        <div class="product-details">
            <span class="product-id smaller-r">Product ID</span>
            <h2 class="bold">Product Name</h2>
            <p class="smaller-b">Starts at ₱ 00.00</p>
        </div>
    </div>

    <div class="product-card" data-modal="add-item-modal">
        <div class="thumbnail">
            <img src="https://drive.google.com/thumbnail?id=0B6wwyazyzml-OGQ3VUo0Z2thdmc&sz=w1000" alt="" class="thumbnail">
        </div>
        <div class="product-details">
            <span class="product-id smaller-r">Product ID</span>
            <h2 class="bold">Product Name</h2>
            <p class="smaller-b">Starts at ₱ 00.00</p>
        </div>
    </div>
</div>
{% endblock %}

{% block modals %}
<div class="modal-container" id="add-item-modal">
    <div class="modal product-view">
        <div class="horizontal-section">
            <div class="vertical-section">
                <div class="slideshow-container">
                    <!-- Full-width images with number and caption text -->
                    <div class="mySlides fade">
                        <img class="img-container" style="aspect-ratio: 3 / 4;" src="https://drive.google.com/thumbnail?id=0B6wwyazyzml-OGQ3VUo0Z2thdmc&sz=w1000">
                    </div>

                    <div class="mySlides fade">
                        <img class="img-container" style="aspect-ratio: 3 / 4;" src="https://drive.google.com/thumbnail?id=0B6wwyazyzml-OGQ3VUo0Z2thdmc&sz=w1000">
                    </div>

                    <div class="mySlides fade">
                        <img class="img-container" style="aspect-ratio: 3 / 4;" src="https://drive.google.com/thumbnail?id=0B6wwyazyzml-OGQ3VUo0Z2thdmc&sz=w1000">
                    </div>
                    <!-- Next and previous buttons -->
                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>
                </div>

                <!-- The dots/circles -->
                <div style="text-align:center">
                    <span class="dot" onclick="currentSlide(1)"></span>
                    <span class="dot" onclick="currentSlide(2)"></span>
                    <span class="dot" onclick="currentSlide(3)"></span>
                </div>
            </div>
            
            <div class="vertical-section">
                <div class="vertical-section" style="align-self: flex-start;">
                    <p class="product-id smaller-r">DW-FT</p>
                    <h1>Frosted Tumbler</h1>
                    <p class="small-r">Category: <b>Individual Items</b></p>
                    <p class="small-r">MOQ: <b>50 pcs.</b></p>
                    <p class="small-r">Starting Price: <b>₱ 0.00</b></p>

                    <div class="divider">
                        <p>Product Description</p>
                        <hr>
                    </div>
                    <div class="product-highlight" style="align-self: stretch;">
                        <p class="small-r">Plastic Material, Capacity: 600 mL</p>
                    </div>

                    <div class="divider">
                        <p>Customization</p>
                        <hr>
                    </div>
                    <div class="horizontal-input-field">
                        <label for="color">Color</label>
                        <select name="color" id="color" class="input"></select>
                    </div>

                    <div class="horizontal-input-field radio-choices">
                        <div class="horizontal-input-field" style="white-space: nowrap; flex: 0;">
                            <input type="radio" name="customization" id="embroider" checked>
                            <label for="embroider">Embroider</label>
                        </div>

                        <div class="horizontal-input-field" style="white-space: nowrap; flex: 0;">
                            <input type="radio" name="customization" id="engrave">
                            <label for="engrave">Engrave</label>
                        </div>
                        
                        <div class="horizontal-input-field" style="white-space: nowrap; flex: 0;">
                            <input type="radio" name="customization" id="print">
                            <label for="print">Print</label> 
                        </div>

                        <div class="horizontal-input-field" style="white-space: nowrap; flex: 0;">
                            <input type="radio" name="customization" id="stamp">
                            <label for="stamp">Stamp</label> 
                        </div>
                        
                        <div class="horizontal-input-field" style="white-space: nowrap; flex: 0;">
                            <input type="radio" name="customization" id="sticker">
                            <label for="sticker">Sticker</label> 
                        </div>

                        <div class="horizontal-input-field" style="white-space: nowrap; flex: 0;">
                            <input type="radio" name="customization" id="none">
                            <label for="none">N/A</label> 
                        </div>        
                    </div>
                </div>

                <div class="vertical-input-field">
                    <label for="note">Note:</label>
                    <input type="text" id="note" name="note" class="input">
                </div>
                <div class="horizontal-input-field" style="align-self: flex-start; flex: 0;">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" min="1" placeholder="1" class="input">
                </div>

                <div class="divider">
                    <hr>
                </div>
                <div class="buttons-section">
                    <button type="button" class="close-modal button-secondary small-m">Close</button>
                    <a href="" class="button-primary small-m">Add Item</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

BVTCApp/templates/bvtc_app/catalog.html
{% extends 'bvtc_app/base.html' %}
{% load static %}

{% block title %}Catalog{% endblock %}

{% block nav %}
<h1 class="bold">Catalog</h1>
{% endblock %}

{% block catalog_button %}
<button type="submit" style="background: #E9E6E3;">
    <i class="material-symbols-rounded" style="font-size: 24px;">browse</i>
    <p class="button-text small-b">Catalog</p>
</button>
{% endblock %}

{% block main %}
<div class="action-bar">
    <div class="horizontal-section">
        <form action="" class="filter" style="flex-wrap: wrap;">
            <p class="small-r filter-name" style="padding: 6px 15px 6px 0px;">Filter:</p>
            <input class="filter-input" type="radio" name="filter" value="all" id="all" checked>
            <label class="filter-label small-b" for="all">All</label>

            <input class="filter-input" type="radio" name="filter" value="company-profile" id="company-profile">
            <label class="filter-label small-b" for="company-profile">Company Profile</label>

            <input class="filter-input" type="radio" name="filter" value="individual-items" id="individual-items">
            <label class="filter-label small-b" for="individual-items">Individual Items</label>

            <input class="filter-input" type="radio" name="filter" value="gift-set" id="gift-set">
            <label class="filter-label small-b" for="gift-set">Gift Set</label>

            <input class="filter-input" type="radio" name="filter" value="bag" id="bag">
            <label class="filter-label small-b" for="bag">Bag</label>
        </form>

        <div class="actions">
            <form action="" class="search-area">
                <input type="search" class="search-bar" placeholder="Search">
            </form>
            <button class="button-primary small-m" data-modal="add-product-modal"><i class="material-symbols-outlined" style="font-size: 15px;">add</i>Add Product</button>
        </div>
    </div>
</div>

<div class="catalog">
    {% for p in products %}
    <div class="product-card open-modal" data-modal="product-modal-{{ p.product_id }}">
        <div class="thumbnail">
            {% with p.productimage_set.first as img %}
                {% if img %}
                    <img src="{{ img.product_image.url }}" alt="{{ p.product_name }}" class="thumbnail">
                {% else %}
                    <img src="" alt="No Image" class="thumbnail">
                {% endif %}
            {% endwith %}
        </div>
        <div class="product-details">
            <span class="product-id smaller-r">{{ p.product_code }}</span>
            <h2 class="bold">{{ p.product_name }}</h2>
            <p class="smaller-b">Starts at ₱ {{ p.starting_price }}</p>
        </div>

        <div class="modal-container" id="product-modal-{{ p.product_id }}">
            <div class="modal product-view">
                <div class="horizontal-section">
                    <div class="vertical-section">
                        <div class="slideshow-container">
                            {% for img in p.productimage_set.all %}
                            <div class="mySlides fade">
                                <img class="img-container" src="{{ img.product_image.url }}" alt="{{ p.product_name }}">
                            </div>
                            {% endfor %}
                            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                            <a class="next" onclick="plusSlides(1)">&#10095;</a>
                        </div>

                        <!-- The dots/circles -->
                        <div style="text-align:center">
                            {% for _ in p.productimage_set.all %}
                            <span class="dot" onclick="currentSlide('{{ forloop.counter }}')"></span>
                            {% endfor %}
                        </div>
                    </div>
                    
                    <div class="vertical-section">
                        <p class="product-id smaller-r">{{ p.product_code }}</p>
                        <h1>{{ p.product_name }}</h1>
                        <p class="small-r">Category: <b>{{ p.category }}</b></p>
                        <p class="small-r">MOQ: <b>{{ p.MOQ }} pcs.</b></p>
                        <p class="small-r">Starting Price: <b>₱ {{ p.starting_price }}</b></p>

                        <div class="divider">
                            <p>Product Description</p>
                            <hr>
                        </div>
                        <div class="product-highlight" style="align-self: stretch;">
                            <p class="small-r">{{ p.description }}</p>
                        </div>
                        
                        <div class="divider">
                            <p>Color Variations</p>
                            <hr>
                        </div>
                        <div class="horizontal-input-field">
                            {% for color in p.productcolor_set.all %}
                            <div class="product-highlight">
                                <span style="background: {{ color.product_color }};"></span>
                                <p class="small-r">{{ color.product_color }}</p>
                            </div>
                            {% empty %}
                                <p class="small-r">No colors variations</p>
                            {% endfor %}
                        </div>

                        <div class="divider">
                            <hr>
                        </div>
                        <div class="buttons-section">
                            <a href="" class="button-tertiary small-m">Delete</a>
                            <a href="" class="button-primary small-m">Edit</a>
                            <button type="button" class="close-modal button-secondary small-m">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block modals %}
<div class="modal-container" id="add-product-modal">
    <div class="modal product-form">
        <form action="">
            {% csrf_token %}
            <h1>Add New Product</h1>
            <div class="divider">
                <p>Basic Information</p>
                <hr>
            </div>

            <div class="horizontal-section">
                <div class="vertical-section" style="flex: 1 0 0;">
                    <div class="file-upload">
                        <label>
                            <span class="file-text">Upload Image/s</span>
                            <input name="photos[]" type="file" accept=".png, .jpg, .jpeg" style="display: none;">
                        </label>
                    </div>

                    <div class="file-upload">
                        <label>
                            <span class="file-text">Upload Image/s</span>
                            <input name="photos[]" type="file" accept=".png, .jpg, .jpeg" style="display: none;">
                        </label>
                    </div>

                    <div class="file-upload">
                        <label>
                            <span class="file-text">Upload Image/s</span>
                            <input name="photos[]" type="file" accept=".png, .jpg, .jpeg" style="display: none;">
                        </label>
                    </div>
                </div>

                <div class="vertical-section" style="flex: 2 0 0;">
                    <div class="horizontal-input-field">
                        <label for="product-id">Product ID:</label>
                        <input type="text" id="product-id" name="product-id" class="input" required>
                    </div>

                    <div class="horizontal-input-field">
                        <label for="product-name">Product Name:</label>
                        <input type="text" id="product-name" name="product-name" class="input" required>
                    </div>

                    <div class="horizontal-input-field">
                        <label for="category">Category:</label>
                        <select class="input" name="category" id="category" required>
                            <option value="company-profile">Company Profile</option>
                            <option value="individual-items">Individual Items</option>
                            <option value="gift-set">Gift Set</option>
                            <option value="bag">Bag</option>
                        </select>
                    </div>
                </div>
            </div>
            
            <div class="vertical-input-field">
                <label for="product-description">Product Description:</label>
                <input type="text" class="input" name="product-description" id="product-description">
            </div>

            <div class="divider">
                <p>Sales Information</p>
                <hr>
            </div>

            <div class="horizontal-section">
                <div class="horizontal-input-field">
                    <label for="moq">MOQ:</label>
                    <input class="input" type="number" min="1" placeholder="1" name="moq" id="moq" required>
                </div>

                <div class="horizontal-input-field">
                    <label for="starting-price">Starting Price:</label>
                    <input class="input" type="number" min="1" placeholder="1" name="starting-price" id="starting-price" required>
                </div>
            </div>

            <div class="vertical-input-field">
                <label for="colors">Color Variations:</label>
                <div class="horizontal-input-field" style="flex-wrap: wrap;">
                    <input class="input" type="text" placeholder="#000000" id="colors" name="colors[]" style="min-width: 90px;">
                    <input class="input" type="text" placeholder="#000000" id="colors" name="colors[]" style="min-width: 90px;">
                    <input class="input" type="text" placeholder="#000000" id="colors" name="colors[]" style="min-width: 90px;">
                    <input class="input" type="text" placeholder="#000000" id="colors" name="colors[]" style="min-width: 90px;">
                </div>
            </div>

            <div class="divider">
                <hr>
            </div>

            <div class="buttons-section">
                <button type="button" class="close-modal button-secondary small-m">Cancel</button>
                <button type="submit" class="button-primary small-m">Add Product</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

BVTCApp/templates/bvtc_app/home.html
{% extends 'bvtc_app/base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block nav %}
{% endblock %}

BVTCApp/templates/bvtc_app/quotations.html
{% extends 'bvtc_app/base.html' %}
{% load static %}

{% block title %}Quotations{% endblock %}

{% block nav %}
<h1 class="bold">Quotations</h1>
{% endblock %}

{% block quotations_button %}
<button type="submit" style="background: #E9E6E3;">
    <i class="material-symbols-rounded" style="font-size: 24px;">request_quote</i>
    <p class="button-text small-b">Quotations</p>
</button>
{% endblock %}